version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_DB_NAME=appmongodb
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network
volumes:
  mongo-data:
    external: true

networks:
  app-network:

# docker run -it --network APPMONGO --name mongodb -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=mongodb -e MONGO_INITDB_ROOT_PASSWORD=admin123 -v VOLMONGO mongo
# mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb